[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
func_attrs_with_params_multiline = true 
quote_style = "double"
number_underscore = "thousands"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config